# Generated by Django 2.0.13 on 2019-05-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=20)),
                ('lat', models.FloatField(default=True)),
                ('lng', models.FloatField(default=True)),
                ('phone_num', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Finder_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('phone_num', models.CharField(max_length=1000)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('posted_due', models.DateField()),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('imageurl', models.CharField(blank=True, default='media/default_image.jpg', max_length=2000, null=True)),
                ('find_time', models.DateTimeField()),
                ('dog_feature', models.TextField()),
                ('dog_type', models.CharField(max_length=200)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Dog_shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('phone_num', models.CharField(max_length=1000)),
                ('lat', models.FloatField(default=True)),
                ('lng', models.FloatField(default=True)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('posted_due', models.DateField()),
                ('image', models.TextField(blank=True, default='', null=True)),
                ('imageurl', models.CharField(blank=True, default='media/default_image.jpg', max_length=2000, null=True)),
                ('dog_name', models.CharField(max_length=200)),
                ('dog_sex', models.IntegerField()),
                ('dog_type', models.CharField(max_length=200)),
                ('lost_time', models.DateTimeField()),
                ('dog_age', models.IntegerField()),
                ('dog_feature', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.IntegerField(default=0)),
                ('key', models.CharField(default='', max_length=1000)),
                ('nickname', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
