# Generated by Django 2.0.13 on 2019-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder_post',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner_post',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
