# Generated by Django 2.0.13 on 2019-05-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190519_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder_post',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='finder_post',
            name='imageurl',
            field=models.CharField(blank=True, default='http://210.107.198.174:8000/media/default_image.jpg', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='finder_post',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Dog_shelter'),
        ),
        migrations.AlterField(
            model_name='owner_post',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='owner_post',
            name='imageurl',
            field=models.CharField(blank=True, default='http://210.107.198.174:8000/media/default_image.jpg', max_length=2000, null=True),
        ),
    ]
