# Generated by Django 2.0.13 on 2019-05-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20190519_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='finder_post',
            name='shelter_name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
