# Generated by Django 2.0.13 on 2019-05-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField()),
                ('view_cnt', models.IntegerField()),
                ('contents', models.TextField()),
                ('write', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LDapp.Post')),
            ],
        ),
    ]
