# Generated by Django 2.0.13 on 2019-05-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adfil',
            field=models.FloatField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.FloatField(default=True, null=True),
        ),
    ]
