# Generated by Django 2.0.13 on 2019-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0003_auto_20190509_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pw', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='write',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
