# Generated by Django 2.0.13 on 2019-05-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0004_auto_20190509_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=20)),
                ('shelter_loc', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Finder_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=20)),
                ('find_time', models.DateTimeField()),
                ('find_loc', models.CharField(max_length=20)),
                ('dog_feature', models.TextField()),
                ('dog_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=20)),
                ('lost_location', models.CharField(max_length=20)),
                ('dog_name', models.CharField(max_length=20)),
                ('dog_sex', models.IntegerField()),
                ('dog_type', models.CharField(max_length=20)),
                ('lost_time', models.DateTimeField()),
                ('dog_age', models.IntegerField()),
                ('dog_feature', models.TextField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=10)),
                ('detail', models.TextField()),
                ('report_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='adfil',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='post_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='write',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Post'),
        ),
    ]
