# Generated by Django 2.0.13 on 2019-05-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0005_auto_20190513_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='write',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Users'),
        ),
    ]
