# Generated by Django 2.0.13 on 2019-05-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0006_auto_20190513_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postMatching', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Post')),
                ('userMatching', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Users')),
            ],
        ),
        migrations.AddField(
            model_name='finder_post',
            name='shelter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Dog_shelter'),
        ),
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Post'),
        ),
        migrations.AddField(
            model_name='report',
            name='userReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Users'),
        ),
    ]
