# Generated by Django 2.0.13 on 2019-05-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0007_auto_20190513_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder_post',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Dog_shelter', unique=True),
        ),
    ]
