# Generated by Django 2.0.13 on 2019-05-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0008_auto_20190513_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_post',
            name='id',
        ),
        migrations.AddField(
            model_name='owner_post',
            name='post_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LDapp.Post'),
        ),
    ]
