# Generated by Django 2.0.13 on 2019-05-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0009_auto_20190513_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner_post',
            old_name='post_id',
            new_name='postOwner',
        ),
        migrations.RemoveField(
            model_name='finder_post',
            name='id',
        ),
        migrations.AddField(
            model_name='finder_post',
            name='postFinder',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LDapp.Post'),
        ),
    ]
