# Generated by Django 2.0.13 on 2019-05-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0010_auto_20190513_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder_post',
            name='postFinder',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LDapp.Post'),
        ),
        migrations.AlterField(
            model_name='finder_post',
            name='shelter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LDapp.Dog_shelter'),
        ),
        migrations.AlterField(
            model_name='owner_post',
            name='postOwner',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LDapp.Post'),
        ),
    ]
