# Generated by Django 2.0.13 on 2019-05-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0011_auto_20190513_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder_post',
            name='postFinder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LDapp.Post'),
        ),
    ]
