# Generated by Django 2.0.13 on 2019-05-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0014_auto_20190513_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder_post',
            name='shelter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LDapp.Dog_shelter'),
        ),
    ]
