# Generated by Django 2.0.13 on 2019-05-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0015_auto_20190513_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
