# Generated by Django 2.0.13 on 2019-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDapp', '0016_auto_20190515_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
